### ISSUE TITLE
如何更新loader？

### ISSUE THREAD

**Issue by tennc** [x-Ai/BurpSuiteLoader#1]
看到了 《XX burp-loader-keygen-2.jar》 这篇文章说是，需要匹配到原始的版本不知道如何找到bp的原始版本，大佬是否能说下？？如何修改loader 使其能继续用到bp最新版上？

**Comment by x-Ai** [comment]
请读Readme.md，当前2020.4版本loader依旧可以使用，只要不改变算法，后续Burp版本可以均可实现引导加载。
