### ISSUE TITLE
通杀注册机造成新的重大Bug

### ISSUE THREAD

**Issue by Asura88** [x-Ai/BurpSuiteLoader#2]
就我所知，通杀注册机造成新的重大Bug。

1.严重影响了界面，影响显示效果。

2.在Repeater中，会造成字符和光标重合问题，严重的光标压根无法实现定位字符位置。

**Comment by x-Ai** [comment]
注册机不会导致Burp界面显示问题，猜测您使用的Windows系统并且修改了Display - Font。

**Comment by Asura88** [comment]
那么，我要如何操作？确实使用的Windows系统并且修改了User options - Display - Font。但是，同样的配置在上一个版本，用的52的注册机是没有问题的。求指教。

2.在Repeater中，会造成字符和光标重合问题，严重的光标压根无法实现定位字符位置。

**Comment by x-Ai** [comment]
在之前BurpSuite 2020.2.1版本在windows平台我遇到了同样的。
如果你看过BurpSuite的更新日志及社区反馈，你就可以知道这是因为PortSwigger为了性能问题删除了很多字体，他们承诺在后续会逐步添加。建议在windows下使用默认即可，如果有更好的方式解决，欢迎分享。
