### ISSUE TITLE
error:no main manifest attribute, in BurpSuiteLoader.jar

### ISSUE THREAD

**Issue by miffyrcee** [x-Ai/BurpSuiteLoader#3]
请问我使用 ` java -jar BurpSuiteLoader.jar`
显示错误`no main manifest attribute, in BurpSuiteLoader.jar`
我应该如何空白安装呀，大佬？

**Comment by miffyrcee** [comment]
我发现可以使用旧版本的loader生成license，然后再使用
`java -noverify -javaagent:BurpSuiteLoader.jar -jar burpsuite_pro_v2020.x.jar`
进而完成注册，我的jdk版本`11`

**Comment by x-Ai** [comment]
> 我发现可以使用旧版本的loader生成license，然后再使用
> `java -noverify -javaagent:BurpSuiteLoader.jar -jar burpsuite_pro_v2020.x.jar`
> 进而完成注册，我的jdk版本`11`
这样才是正确的方式👌

**Comment by x-Ai** [comment]
> 我发现可以使用旧版本的loader生成license，然后再使用
> 
> `java -noverify -javaagent:BurpSuiteLoader.jar -jar burpsuite_pro_v2020.x.jar`
> 
> 进而完成注册，我的jdk版本`11`

这样才是正确的使用方式👌

**Comment by miffyrcee** [comment]
好的 谢谢
