### ISSUE TITLE
burpsuite want license key

### ISSUE THREAD

**Issue by connected201** [x-Ai/BurpSuiteLoader#4]
hi, i installed java 13 on kubuntu 20.4, and burpsuite want license key.
![image](https://user-images.githubusercontent.com/20506433/80954691-8c1ed400-8e06-11ea-91ea-8c83cec14fdb.png)
 how to fix it? best regards

**Comment by x-Ai** [comment]
Hello, please use the old version of loader-keygen to generate the license you need。

**Comment by connected201** [comment]
where i can find this old loader-keygen?

**Comment by x-Ai** [comment]
search surferxyz loader.
