### ISSUE TITLE
Not worked!

### ISSUE THREAD

**Issue by Habibu-R-ahman** [x-Ai/BurpSuiteLoader#5]
It requires Licence key

**Comment by raddyfiy** [comment]
Use this new loader start, then use old version keygen to register. It works.

**Comment by abdul-550** [comment]
from where i get old version keygen

**Comment by abdul-550** [comment]
it worked thnks man
here is keygen:
https://drive.google.com/drive/folders/1Y7sZRcHxhISqDebaLx18yNZYGaLstKYG

java -jar (filepath)/BurpKeygen.jar

**Comment by Numenorean** [comment]
> it worked thnks man
> here is keygen:
> https://drive.google.com/drive/folders/1Y7sZRcHxhISqDebaLx18yNZYGaLstKYG
> 
> java -jar (filepath)/BurpKeygen.jar

thanks so much. now it works

**Comment by vlakhani28** [comment]
![Capture](https://user-images.githubusercontent.com/42069316/87849728-70f13a00-c908-11ea-96fc-b0864638a5aa.PNG)

What do i do now..

If i manually put the licence key it tells me to go on portswinger website

Can u pls help

**Comment by m0ni01** [comment]
java -noverify -javaagent:(path)/BurpSuiteLoader.jar -jar
/home/moni/Downloads/Burp/burp/Setup/burpsuite_pro_v2020
