### ISSUE TITLE
Loader not generating License Key

### ISSUE THREAD

**Issue by agentshevy** [x-Ai/BurpSuiteLoader#8]
Loader not generating a License Key to be used. When I run the command, it comes up with an Empty box.

![Capture](https://user-images.githubusercontent.com/64799626/82742195-bf43eb80-9d52-11ea-838d-6a66a720b0d2.PNG)

**Comment by x-Ai** [comment]
Hello, please use the old version of loader-keygen to generate the license you need。search surferxyz loader.

**Comment by ToxicParticle** [comment]
hi there, for that you need to download JDK 8 or older and you need an older version of java. isn't there a way to do this with latest environment?

**Comment by x-Ai** [comment]
> hi there, for that you need to download JDK 8 or older and you need an older version of java. isn't there a way to do this with latest environment?

PortSwigger dropped BurpSuite support for Java 8

**Comment by ToxicParticle** [comment]
ok. so is there any alternative?

**Comment by x-Ai** [comment]
> ok. so is there any alternative?

using versions prior to 2020.4.1

**Comment by twins16** [comment]
support for Java 8

**Comment by Shen897** [comment]
I got the same problem too. 

@x-Ai What the latest Java environment lack that prevent the developers from port/update BurpSuiteLoader to the latest environment?

**Comment by x-Ai** [comment]
> I got the same problem too.
> 
> @x-Ai What the latest Java environment lack that prevent the developers from port/update BurpSuiteLoader to the latest environment?

The probability of Burpsuite dropping java8 is that it needs to use a higher version of the java feature.

**Comment by Shen897** [comment]
I think I need to rephrase my statement to make it clear.

What prevent you from updating `BurpSuiteLoader` to java 11 or java 14?  
The latest version of Burp Suite pro require  java 11 and above 

Making `BurpSuiteLoader` work on JDK 11+ is necessary.
